variable "lab_prefix" {
  description = "Unique prefix generated by setup."
  type        = string
}

variable "aws_region" {
  description = "Region used by the AWS provider."
  type        = string
}

variable "localstack_endpoint" {
  description = "LocalStack endpoint for S3 and IAM."
  type        = string
}

variable "ec2_endpoint" {
  description = "LocalStack endpoint used by EC2 resources and data sources."
  type        = string
}

