variable "lab_prefix" {
  description = "Unique prefix generated by the setup script."
  type        = string
  default     = "tfr04-placeholder"

  validation {
    condition     = can(regex("^[a-z0-9-]+$", var.lab_prefix))
    error_message = "lab_prefix must contain lowercase letters, digits, and hyphens only."
  }
}

variable "aws_region" {
  description = "Region used by the LocalStack simulation."
  type        = string
  default     = "us-east-1"
}

variable "localstack_endpoint" {
  description = "Base LocalStack edge endpoint."
  type        = string
  default     = "http://127.0.0.1:4566"
}
