terraform {
  required_version = ">= 1.11.0, < 1.12.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.70.0"
    }
  }
}


variable "archive_bucket_name" {
  type        = string
  description = "Existing LocalStack bucket name generated by the setup script."
}

locals {
  localstack_endpoint = "http://localhost:4566"
}

# Temporary default provider left behind by the interrupted refactor.
provider "aws" {
  region                      = "us-east-1"
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true

  endpoints {
    autoscaling = local.localstack_endpoint
    ec2         = local.localstack_endpoint
    iam         = local.localstack_endpoint
    s3          = local.localstack_endpoint
    sts         = local.localstack_endpoint
  }
}

provider "aws" {
  alias  = "compute"
  region = "us-east-1"

  profile                  = "compute-admin"
  shared_config_files      = ["${path.module}/.aws/configs"]
  shared_credentials_files = ["${path.module}/.aws/credential"]

  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true

  endpoints {
    autoscaling = local.localstack_endpoint
    ec2         = local.localstack_endpoint
    iam         = local.localstack_endpoint
    s3          = local.localstack_endpoint
    sts         = local.localstack_endpoint
  }
}

provider "aws" {
  alias  = "identity"
  region = "us-east-1"

  profile                  = "identity-maintainer"
  shared_config_files      = ["${path.module}/.aws/configs"]
  shared_credentials_files = ["${path.module}/.aws/credential"]

  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true

  endpoints {
    autoscaling = local.localstack_endpoint
    ec2         = local.localstack_endpoint
    iam         = local.localstack_endpoint
    s3          = local.localstack_endpoint
    sts         = local.localstack_endpoint
  }
}

module "compute" {
  source = "./modules/compute"
}

module "identity" {
  source = "./modules/identity"
}

module "storage" {
  source = "./modules/storage"

  bucket_name = var.archive_bucket_name
}

data "aws_caller_identity" "current" {}

resource "aws_s3_bucket_object" "legacy_artifact" {
  bucket       = module.storage.bucket_name
  key          = "artifact.txt"
  content      = "ORIGINAL-CONTENT"
  content_type = "text/plain"
  etag         = md5("ORIGINAL-CONTENT")
}

resource "aws_s3_object" "artifact" {
  bucket       = module.storage.bucket_name
  key          = "artifact.txt"
  content      = "ORIGINAL-CONTENT\n"
  content_type = "text/plain"
  etag         = md5("ORIGINAL-CONTENT\n")
}

output "audited_account_id" {
  value = data.aws_caller_identity.current.account_id
}
